BSPD-1048: Content Delivery: Colors
brightspot/react-examples pull request #26
Opened 2022-09-01 16:53 UTC by haase1020

2022-09-12 14:24 UTC, danslaughter2 requested changes
This is a test. Please resolve this.

2022-09-12 14:28 UTC, danslaughter2 approved these changes

2022-09-12 15:03 UTC, danslaughter2 requested changes

2022-09-12 15:03 UTC, danslaughter2 commented on colors/app/src/components/Colors/index.tsx
> +            : colorResponse?.colorData?.hexValue}
Should extract name and hexValue to a couple local vars to reduce the duplication a bit.

2022-09-12 15:03 UTC, danslaughter2 commented on colors/brightspot/src/brightspot/example/colors/Color.ts
> +  @JavaField(String)
Should use the ColorPicker annotation here for better CMS experience, especially since there's nothing that calls out specifically that the hex code must be preceded with a `#`.

2022-09-12 15:03 UTC, danslaughter2 commented on colors/brightspot/src/brightspot/example/colors/Color.ts
> +@DisplayName({ value: 'Color' })
Not necessary since this matches the class name already.

2022-09-12 15:03 UTC, danslaughter2 commented on colors/brightspot/src/brightspot/example/colors/Color.ts
> +  hex_value?: string
Creating a java class so please use camelCase for var names.

2022-09-12 15:03 UTC, danslaughter2 commented on colors/brightspot/src/brightspot/example/colors/ColorEndpoint.ts
> +  }
I prefer to have getPaths as the first method in the class. Also make sure the README's list of functions is consistent with the ordering here.

2022-09-12 15:03 UTC, danslaughter2 commented on colors/brightspot/src/brightspot/example/colors/ColorEndpoint.ts
> +export default class ColorEndpoint extends JavaClass(
Should have a space between these 2 lines.

2022-09-12 21:05 UTC, haase1020 commented
Moved to draft since directory names should match application feature

2022-10-03 16:33 UTC, danslaughter2 approved these changes

2022-10-04 15:58 UTC, merged